name: Apply schema migrations

on:
  push:
    branches:
      - main
      
jobs:
  apply_migrations:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install dependencies & tooling
        run: |
          npm install
          npm install -g drizzle-orm drizzle-kit pg vercel
      - name: Pull Vercel environment variables
        run: |
          vercel env pull --environment=production .env.local --token ${{ secrets.VERCEL_TOKEN }} --org ${{ secrets.VERCEL_ORG_ID }} --project ${{ secrets.VERCEL_PROJECT_ID }}
      - name: Apply migrations
        run: drizzle-kit migrate
